---
# linux install jdk and httpd

- hosts: all
  gather_facts: true
  become: true
  roles:
# install jdk 
  - name: install jdk
    role: Java
    tags:
      - Java
# install httpd
  - name: install httpd services
    role: httpd
    tags:
      - httpd
