---
# linux install jdk and httpd

- hosts: all
  gather_facts: true
  become: true
  roles:
# install jdk 
  - name: install jdk
    role: krishkakumani/Java
    tags:
      - java
# install httpd
  - name: install httpd services
    role: krishkakumani/httpd
    tags:
      - httpd
